version: "3.2"

services:
  reverseproxy:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "443:443" 
      - "80:80" 
    restart: always
  node-subtensor:
    depends_on:
      - reverseproxy 
    container_name: node-subtensor
    image: opentensorfdn/subtensor:latest
    cpu_count: 2
    mem_limit: 2000000000
    memswap_limit: 4000000000
    ports:
      - "9944:9944"
      - "30333:30333"
      - "9933:9933"
    environment:
      - CARGO_HOME=/var/www/node-subtensor/.cargo
    command: bash -c "/usr/local/bin/node-subtensor --base-path /root/.local/share/node-subtensor/ --chain /subtensor/specs/nakamotoSpecRaw.json --rpc-external --ws-external --rpc-cors all --no-mdns --ws-max-connections 1000 --in-peers 500 --out-peers 500"
